{
    'name': 'Bike Workshop',
    'version': '19.0.1.0.2',
    'category': 'Services',
    'summary': 'Manage bikes and daily rental operations for Ramis workshop',
    'depends': ['base', 'mail', 'product', 'website', 'portal'],  
    'data': [
        'security/bike_workshop_security.xml',
        'security/ir.model.access.csv',
        'views/bike_views.xml',
        'views/product_views.xml',
        'data/rental_sequence.xml',
        'data/repair_sequence.xml',
        'views/rental_views.xml',
        'views/repair_views.xml',
        'views/res_partner_views.xml',
        'reports/rental_agreement_report.xml',
        'views/portal_templates.xml',
        'views/rental_report_views.xml',
        'views/dashboard_views.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}